### ISSUE TITLE
doesn't serve file when expected

### ISSUE THREAD

**Issue by peetklecha** [herudi/static-files#1]
i was experiencing a problem where the library was not working as expected to serve a file that was clearly present/being requested. i was able to fix the issue locally by modifying line 98 of /src/utils.ts:

```js
      (contentType(pathFile.replace("/", "\\")) || "application/octet-stream"),
```

i changed it to:

```js
      (contentType(pathFile.replaceAll("/", "")) || "application/octet-stream"),
```

and it began to work. however, i'm not sure this is really the best fix. the real problem, it seems to me, is that it is calling `contentType` on `pathFile` (the full absolute file path) rather than just the filename (`index.js` or whatever).

**Comment by herudi** [comment]
ah, ok. in line 98, read extension for finded content type. maybe fail with `\\` for other unix. 
can you please make a PR ?
